package com.healthcare.db;

import java.sql.*;

public class SchemaInitializer {

    public static void initialize() {
        Connection conn = DatabaseConnection.getInstance().getConnection();
        try (Statement st = conn.createStatement()) {
            // Users
            st.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id TEXT PRIMARY KEY,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL
                )
            """);
            // Patients
            st.execute("""
                CREATE TABLE IF NOT EXISTS patients (
                    user_id TEXT PRIMARY KEY,
                    dob TEXT,
                    insurance_id TEXT,
                    allergies TEXT,
                    FOREIGN KEY(user_id) REFERENCES users(user_id)
                )
            """);
            // Staff (receptionist, clinician, pharmacist, admin)
            st.execute("""
                CREATE TABLE IF NOT EXISTS staff (
                    user_id TEXT PRIMARY KEY,
                    staff_id TEXT,
                    licence_no TEXT,
                    speciality TEXT,
                    reg_no TEXT,
                    pharmacy TEXT,
                    shift TEXT,
                    admin_level TEXT,
                    FOREIGN KEY(user_id) REFERENCES users(user_id)
                )
            """);
            // Appointments
            st.execute("""
                CREATE TABLE IF NOT EXISTS appointments (
                    appointment_id TEXT PRIMARY KEY,
                    patient_id TEXT NOT NULL,
                    clinician_id TEXT NOT NULL,
                    scheduled_at TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PENDING',
                    FOREIGN KEY(patient_id) REFERENCES patients(user_id),
                    FOREIGN KEY(clinician_id) REFERENCES users(user_id)
                )
            """);
            // Medical Records
            st.execute("""
                CREATE TABLE IF NOT EXISTS medical_records (
                    record_id TEXT PRIMARY KEY,
                    patient_id TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT,
                    archived_at TEXT,
                    state TEXT NOT NULL DEFAULT 'CREATED',
                    FOREIGN KEY(patient_id) REFERENCES patients(user_id)
                )
            """);
            st.execute("ALTER TABLE medical_records ADD COLUMN IF NOT EXISTS updated_at TEXT");
            st.execute("ALTER TABLE medical_records ADD COLUMN IF NOT EXISTS archived_at TEXT");
            st.execute("""
                CREATE TABLE IF NOT EXISTS medical_record_notes (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    record_id TEXT NOT NULL,
                    note TEXT NOT NULL,
                    FOREIGN KEY(record_id) REFERENCES medical_records(record_id)
                )
            """);
            // Drugs
            st.execute("""
                CREATE TABLE IF NOT EXISTS drugs (
                    drug_code TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    contraindications TEXT
                )
            """);
            // Prescriptions
            st.execute("""
                CREATE TABLE IF NOT EXISTS prescriptions (
                    rx_id TEXT PRIMARY KEY,
                    appointment_id TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'DRAFT',
                    issued_at TEXT,
                    override_reason TEXT,
                    FOREIGN KEY(appointment_id) REFERENCES appointments(appointment_id)
                )
            """);
            // Prescription Items
            st.execute("""
                CREATE TABLE IF NOT EXISTS prescription_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    rx_id TEXT NOT NULL,
                    drug_code TEXT NOT NULL,
                    dosage TEXT,
                    frequency TEXT,
                    duration_days INTEGER,
                    FOREIGN KEY(rx_id) REFERENCES prescriptions(rx_id),
                    FOREIGN KEY(drug_code) REFERENCES drugs(drug_code)
                )
            """);
            // Audit Log
            st.execute("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    action TEXT NOT NULL,
                    user_id TEXT,
                    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """);
            System.out.println("[DB] Schema initialised.");
        } catch (SQLException e) {
            throw new RuntimeException("Schema init failed", e);
        }
    }
}
